/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AlarmSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const Alarm = IDL.Record({
  'id' : IDL.Text,
  'pressId' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timestamp' : Time,
  'severity' : AlarmSeverity,
});
export const CostMetrics = IDL.Record({
  'powerConsumptionKwh' : IDL.Float64,
  'pressId' : IDL.Text,
  'date' : Time,
  'labourEfficiencyPct' : IDL.Float64,
  'energyCostPerMT' : IDL.Float64,
  'revenuePerPressPerDay' : IDL.Float64,
  'productionCostPerMT' : IDL.Float64,
  'scrapCost' : IDL.Float64,
});
export const DieMaintenance = IDL.Record({
  'shotsCompleted' : IDL.Int,
  'changeFrequency' : IDL.Int,
  'maintenanceDue' : Time,
  'dieNo' : IDL.Text,
  'shotLife' : IDL.Int,
  'lastMaintenanceDate' : Time,
});
export const DowntimeCategory = IDL.Variant({
  'dieFailure' : IDL.Null,
  'other' : IDL.Null,
  'operatorDelay' : IDL.Null,
  'billetQuality' : IDL.Null,
  'powerFailure' : IDL.Null,
  'mechanicalFailure' : IDL.Null,
});
export const DowntimeEvent = IDL.Record({
  'id' : IDL.Text,
  'mtbfHours' : IDL.Float64,
  'pressId' : IDL.Text,
  'durationMinutes' : IDL.Int,
  'timestamp' : Time,
  'category' : DowntimeCategory,
  'mttrHours' : IDL.Float64,
});
export const MachineParameters = IDL.Record({
  'exitTemp' : IDL.Float64,
  'billetTemp' : IDL.Float64,
  'pressId' : IDL.Text,
  'mainRamPressure' : IDL.Float64,
  'containerTemp' : IDL.Float64,
  'dieTemp' : IDL.Float64,
  'timestamp' : Time,
  'extrusionPressure' : IDL.Float64,
  'ramSpeed' : IDL.Float64,
  'pullerForce' : IDL.Float64,
  'breakthroughPressure' : IDL.Float64,
});
export const OEEData = IDL.Record({
  'rejectionPct' : IDL.Float64,
  'reworkPct' : IDL.Float64,
  'scrapKg' : IDL.Float64,
  'dieChangeTime' : IDL.Float64,
  'pressId' : IDL.Text,
  'standardSpeed' : IDL.Float64,
  'idleTime' : IDL.Float64,
  'pressEfficiencyPct' : IDL.Float64,
  'breakdownTime' : IDL.Float64,
  'outputVsRatedCapacityPct' : IDL.Float64,
  'firstPassYieldPct' : IDL.Float64,
  'qualityPct' : IDL.Float64,
  'timestamp' : Time,
  'availabilityPct' : IDL.Float64,
  'setupTime' : IDL.Float64,
  'plannedRunTime' : IDL.Float64,
  'oeePct' : IDL.Float64,
  'actualRunTime' : IDL.Float64,
  'actualSpeed' : IDL.Float64,
  'performancePct' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'delayed' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'completedMT' : IDL.Float64,
  'totalMT' : IDL.Float64,
  'dueDate' : Time,
  'workOrderNo' : IDL.Text,
  'plantId' : IDL.Text,
  'alloyGrade' : IDL.Text,
  'dieNo' : IDL.Text,
});
export const Plant = IDL.Record({
  'id' : IDL.Text,
  'capacityUtilizationPct' : IDL.Float64,
  'totalCapacityMT' : IDL.Float64,
  'name' : IDL.Text,
  'oeePct' : IDL.Float64,
  'location' : IDL.Text,
  'activePresses' : IDL.Int,
});
export const PressStatus = IDL.Variant({
  'idle' : IDL.Null,
  'breakdown' : IDL.Null,
  'setup' : IDL.Null,
  'running' : IDL.Null,
});
export const Press = IDL.Record({
  'id' : IDL.Text,
  'status' : PressStatus,
  'activeDie' : IDL.Text,
  'name' : IDL.Text,
  'operatorName' : IDL.Text,
  'shift' : IDL.Text,
  'currentOrder' : IDL.Text,
  'alloyGrade' : IDL.Text,
  'plant' : IDL.Text,
});
export const ProductionMetrics = IDL.Record({
  'recoveryPct' : IDL.Float64,
  'containerChangeTime' : IDL.Float64,
  'pressId' : IDL.Text,
  'cycleTimePerBillet' : IDL.Float64,
  'pullerSpeed' : IDL.Float64,
  'totalProductionMT' : IDL.Float64,
  'pressKgPerHour' : IDL.Float64,
  'dailyTargetMT' : IDL.Float64,
  'sawCycleTime' : IDL.Float64,
  'timestamp' : Time,
  'shiftProductionA' : IDL.Float64,
  'shiftProductionB' : IDL.Float64,
  'shiftProductionC' : IDL.Float64,
  'extrusionSpeed' : IDL.Float64,
  'dailyProductionMT' : IDL.Float64,
  'billetCount' : IDL.Int,
});
export const QualityRecord = IDL.Record({
  'rejectionPctByAlloy' : IDL.Float64,
  'customerComplaints' : IDL.Int,
  'scrapCostImpact' : IDL.Float64,
  'pressId' : IDL.Text,
  'dimensionalFailurePct' : IDL.Float64,
  'alloyGrade' : IDL.Text,
  'timestamp' : Time,
  'rejectionPctByDie' : IDL.Float64,
  'dieNo' : IDL.Text,
  'rootCauseSummary' : IDL.Text,
  'surfaceDefectCount' : IDL.Int,
});
export const LivePressRecord = IDL.Record({
  'id' : IDL.Text,
  'oee' : IDL.Float64,
  'status' : IDL.Text,
  'downtimeMinutes' : IDL.Int,
  'contactTime' : IDL.Float64,
  'ppPlanBillets' : IDL.Int,
  'kgPerHour' : IDL.Float64,
  'dieUnloadCount' : IDL.Int,
  'dieLoadCount' : IDL.Int,
  'ppActBillets' : IDL.Int,
  'recovery' : IDL.Float64,
  'dieKgH' : IDL.Float64,
  'inputMt' : IDL.Float64,
  'outputMt' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAlarm' : IDL.Func([Alarm], [], []),
  'addCostMetrics' : IDL.Func([CostMetrics], [], []),
  'addDieMaintenance' : IDL.Func([DieMaintenance], [], []),
  'addDowntimeEvent' : IDL.Func([DowntimeEvent], [], []),
  'addMachineParameters' : IDL.Func([MachineParameters], [], []),
  'addOEEData' : IDL.Func([OEEData], [], []),
  'addOrder' : IDL.Func([Order], [], []),
  'addPlant' : IDL.Func([Plant], [], []),
  'addPress' : IDL.Func([Press], [], []),
  'addProductionMetrics' : IDL.Func([ProductionMetrics], [], []),
  'addQualityRecord' : IDL.Func([QualityRecord], [], []),
  'deletePress' : IDL.Func([IDL.Text], [], []),
  'fetchLiveData' : IDL.Func([], [IDL.Bool, IDL.Text], []),
  'getActiveAlarms' : IDL.Func([], [IDL.Vec(Alarm)], ['query']),
  'getAllPlants' : IDL.Func([], [IDL.Vec(Plant)], ['query']),
  'getAllPresses' : IDL.Func([], [IDL.Vec(Press)], ['query']),
  'getApiEndpoint' : IDL.Func([], [IDL.Text, IDL.Bool], ['query']),
  'getDowntimeEventsByCategory' : IDL.Func(
      [DowntimeCategory],
      [IDL.Vec(DowntimeEvent)],
      ['query'],
    ),
  'getLastFetchStatus' : IDL.Func([], [IDL.Text, IDL.Int], ['query']),
  'getLivePressData' : IDL.Func([], [IDL.Vec(LivePressRecord)], ['query']),
  'getMachineParameters' : IDL.Func([IDL.Text], [MachineParameters], ['query']),
  'getOEEData' : IDL.Func([IDL.Text], [IDL.Vec(OEEData)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getOverdueDies' : IDL.Func([Time], [IDL.Vec(DieMaintenance)], ['query']),
  'getPlant' : IDL.Func([IDL.Text], [Plant], ['query']),
  'getPress' : IDL.Func([IDL.Text], [Press], ['query']),
  'getPressesByPlant' : IDL.Func([IDL.Text], [IDL.Vec(Press)], ['query']),
  'getProductionMetrics' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductionMetrics)],
      ['query'],
    ),
  'getQualityRecordsByAlloy' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QualityRecord)],
      ['query'],
    ),
  'seedSampleData' : IDL.Func([], [], []),
  'setApiEndpoint' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePress' : IDL.Func([Press], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AlarmSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Alarm = IDL.Record({
    'id' : IDL.Text,
    'pressId' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timestamp' : Time,
    'severity' : AlarmSeverity,
  });
  const CostMetrics = IDL.Record({
    'powerConsumptionKwh' : IDL.Float64,
    'pressId' : IDL.Text,
    'date' : Time,
    'labourEfficiencyPct' : IDL.Float64,
    'energyCostPerMT' : IDL.Float64,
    'revenuePerPressPerDay' : IDL.Float64,
    'productionCostPerMT' : IDL.Float64,
    'scrapCost' : IDL.Float64,
  });
  const DieMaintenance = IDL.Record({
    'shotsCompleted' : IDL.Int,
    'changeFrequency' : IDL.Int,
    'maintenanceDue' : Time,
    'dieNo' : IDL.Text,
    'shotLife' : IDL.Int,
    'lastMaintenanceDate' : Time,
  });
  const DowntimeCategory = IDL.Variant({
    'dieFailure' : IDL.Null,
    'other' : IDL.Null,
    'operatorDelay' : IDL.Null,
    'billetQuality' : IDL.Null,
    'powerFailure' : IDL.Null,
    'mechanicalFailure' : IDL.Null,
  });
  const DowntimeEvent = IDL.Record({
    'id' : IDL.Text,
    'mtbfHours' : IDL.Float64,
    'pressId' : IDL.Text,
    'durationMinutes' : IDL.Int,
    'timestamp' : Time,
    'category' : DowntimeCategory,
    'mttrHours' : IDL.Float64,
  });
  const MachineParameters = IDL.Record({
    'exitTemp' : IDL.Float64,
    'billetTemp' : IDL.Float64,
    'pressId' : IDL.Text,
    'mainRamPressure' : IDL.Float64,
    'containerTemp' : IDL.Float64,
    'dieTemp' : IDL.Float64,
    'timestamp' : Time,
    'extrusionPressure' : IDL.Float64,
    'ramSpeed' : IDL.Float64,
    'pullerForce' : IDL.Float64,
    'breakthroughPressure' : IDL.Float64,
  });
  const OEEData = IDL.Record({
    'rejectionPct' : IDL.Float64,
    'reworkPct' : IDL.Float64,
    'scrapKg' : IDL.Float64,
    'dieChangeTime' : IDL.Float64,
    'pressId' : IDL.Text,
    'standardSpeed' : IDL.Float64,
    'idleTime' : IDL.Float64,
    'pressEfficiencyPct' : IDL.Float64,
    'breakdownTime' : IDL.Float64,
    'outputVsRatedCapacityPct' : IDL.Float64,
    'firstPassYieldPct' : IDL.Float64,
    'qualityPct' : IDL.Float64,
    'timestamp' : Time,
    'availabilityPct' : IDL.Float64,
    'setupTime' : IDL.Float64,
    'plannedRunTime' : IDL.Float64,
    'oeePct' : IDL.Float64,
    'actualRunTime' : IDL.Float64,
    'actualSpeed' : IDL.Float64,
    'performancePct' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'delayed' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'completedMT' : IDL.Float64,
    'totalMT' : IDL.Float64,
    'dueDate' : Time,
    'workOrderNo' : IDL.Text,
    'plantId' : IDL.Text,
    'alloyGrade' : IDL.Text,
    'dieNo' : IDL.Text,
  });
  const Plant = IDL.Record({
    'id' : IDL.Text,
    'capacityUtilizationPct' : IDL.Float64,
    'totalCapacityMT' : IDL.Float64,
    'name' : IDL.Text,
    'oeePct' : IDL.Float64,
    'location' : IDL.Text,
    'activePresses' : IDL.Int,
  });
  const PressStatus = IDL.Variant({
    'idle' : IDL.Null,
    'breakdown' : IDL.Null,
    'setup' : IDL.Null,
    'running' : IDL.Null,
  });
  const Press = IDL.Record({
    'id' : IDL.Text,
    'status' : PressStatus,
    'activeDie' : IDL.Text,
    'name' : IDL.Text,
    'operatorName' : IDL.Text,
    'shift' : IDL.Text,
    'currentOrder' : IDL.Text,
    'alloyGrade' : IDL.Text,
    'plant' : IDL.Text,
  });
  const ProductionMetrics = IDL.Record({
    'recoveryPct' : IDL.Float64,
    'containerChangeTime' : IDL.Float64,
    'pressId' : IDL.Text,
    'cycleTimePerBillet' : IDL.Float64,
    'pullerSpeed' : IDL.Float64,
    'totalProductionMT' : IDL.Float64,
    'pressKgPerHour' : IDL.Float64,
    'dailyTargetMT' : IDL.Float64,
    'sawCycleTime' : IDL.Float64,
    'timestamp' : Time,
    'shiftProductionA' : IDL.Float64,
    'shiftProductionB' : IDL.Float64,
    'shiftProductionC' : IDL.Float64,
    'extrusionSpeed' : IDL.Float64,
    'dailyProductionMT' : IDL.Float64,
    'billetCount' : IDL.Int,
  });
  const QualityRecord = IDL.Record({
    'rejectionPctByAlloy' : IDL.Float64,
    'customerComplaints' : IDL.Int,
    'scrapCostImpact' : IDL.Float64,
    'pressId' : IDL.Text,
    'dimensionalFailurePct' : IDL.Float64,
    'alloyGrade' : IDL.Text,
    'timestamp' : Time,
    'rejectionPctByDie' : IDL.Float64,
    'dieNo' : IDL.Text,
    'rootCauseSummary' : IDL.Text,
    'surfaceDefectCount' : IDL.Int,
  });
  const LivePressRecord = IDL.Record({
    'id' : IDL.Text,
    'oee' : IDL.Float64,
    'status' : IDL.Text,
    'downtimeMinutes' : IDL.Int,
    'contactTime' : IDL.Float64,
    'ppPlanBillets' : IDL.Int,
    'kgPerHour' : IDL.Float64,
    'dieUnloadCount' : IDL.Int,
    'dieLoadCount' : IDL.Int,
    'ppActBillets' : IDL.Int,
    'recovery' : IDL.Float64,
    'dieKgH' : IDL.Float64,
    'inputMt' : IDL.Float64,
    'outputMt' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAlarm' : IDL.Func([Alarm], [], []),
    'addCostMetrics' : IDL.Func([CostMetrics], [], []),
    'addDieMaintenance' : IDL.Func([DieMaintenance], [], []),
    'addDowntimeEvent' : IDL.Func([DowntimeEvent], [], []),
    'addMachineParameters' : IDL.Func([MachineParameters], [], []),
    'addOEEData' : IDL.Func([OEEData], [], []),
    'addOrder' : IDL.Func([Order], [], []),
    'addPlant' : IDL.Func([Plant], [], []),
    'addPress' : IDL.Func([Press], [], []),
    'addProductionMetrics' : IDL.Func([ProductionMetrics], [], []),
    'addQualityRecord' : IDL.Func([QualityRecord], [], []),
    'deletePress' : IDL.Func([IDL.Text], [], []),
    'fetchLiveData' : IDL.Func([], [IDL.Bool, IDL.Text], []),
    'getActiveAlarms' : IDL.Func([], [IDL.Vec(Alarm)], ['query']),
    'getAllPlants' : IDL.Func([], [IDL.Vec(Plant)], ['query']),
    'getAllPresses' : IDL.Func([], [IDL.Vec(Press)], ['query']),
    'getApiEndpoint' : IDL.Func([], [IDL.Text, IDL.Bool], ['query']),
    'getDowntimeEventsByCategory' : IDL.Func(
        [DowntimeCategory],
        [IDL.Vec(DowntimeEvent)],
        ['query'],
      ),
    'getLastFetchStatus' : IDL.Func([], [IDL.Text, IDL.Int], ['query']),
    'getLivePressData' : IDL.Func([], [IDL.Vec(LivePressRecord)], ['query']),
    'getMachineParameters' : IDL.Func(
        [IDL.Text],
        [MachineParameters],
        ['query'],
      ),
    'getOEEData' : IDL.Func([IDL.Text], [IDL.Vec(OEEData)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getOverdueDies' : IDL.Func([Time], [IDL.Vec(DieMaintenance)], ['query']),
    'getPlant' : IDL.Func([IDL.Text], [Plant], ['query']),
    'getPress' : IDL.Func([IDL.Text], [Press], ['query']),
    'getPressesByPlant' : IDL.Func([IDL.Text], [IDL.Vec(Press)], ['query']),
    'getProductionMetrics' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductionMetrics)],
        ['query'],
      ),
    'getQualityRecordsByAlloy' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QualityRecord)],
        ['query'],
      ),
    'seedSampleData' : IDL.Func([], [], []),
    'setApiEndpoint' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePress' : IDL.Func([Press], [], []),
  });
};

export const init = ({ IDL }) => { return []; };