/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alarm {
  'id' : string,
  'pressId' : string,
  'description' : string,
  'isActive' : boolean,
  'timestamp' : Time,
  'severity' : AlarmSeverity,
}
export type AlarmSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export interface CostMetrics {
  'powerConsumptionKwh' : number,
  'pressId' : string,
  'date' : Time,
  'labourEfficiencyPct' : number,
  'energyCostPerMT' : number,
  'revenuePerPressPerDay' : number,
  'productionCostPerMT' : number,
  'scrapCost' : number,
}
export interface DieMaintenance {
  'shotsCompleted' : bigint,
  'changeFrequency' : bigint,
  'maintenanceDue' : Time,
  'dieNo' : string,
  'shotLife' : bigint,
  'lastMaintenanceDate' : Time,
}
export type DowntimeCategory = { 'dieFailure' : null } |
  { 'other' : null } |
  { 'operatorDelay' : null } |
  { 'billetQuality' : null } |
  { 'powerFailure' : null } |
  { 'mechanicalFailure' : null };
export interface DowntimeEvent {
  'id' : string,
  'mtbfHours' : number,
  'pressId' : string,
  'durationMinutes' : bigint,
  'timestamp' : Time,
  'category' : DowntimeCategory,
  'mttrHours' : number,
}
export interface MachineParameters {
  'exitTemp' : number,
  'billetTemp' : number,
  'pressId' : string,
  'mainRamPressure' : number,
  'containerTemp' : number,
  'dieTemp' : number,
  'timestamp' : Time,
  'extrusionPressure' : number,
  'ramSpeed' : number,
  'pullerForce' : number,
  'breakthroughPressure' : number,
}
export interface OEEData {
  'rejectionPct' : number,
  'reworkPct' : number,
  'scrapKg' : number,
  'dieChangeTime' : number,
  'pressId' : string,
  'standardSpeed' : number,
  'idleTime' : number,
  'pressEfficiencyPct' : number,
  'breakdownTime' : number,
  'outputVsRatedCapacityPct' : number,
  'firstPassYieldPct' : number,
  'qualityPct' : number,
  'timestamp' : Time,
  'availabilityPct' : number,
  'setupTime' : number,
  'plannedRunTime' : number,
  'oeePct' : number,
  'actualRunTime' : number,
  'actualSpeed' : number,
  'performancePct' : number,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'completedMT' : number,
  'totalMT' : number,
  'dueDate' : Time,
  'workOrderNo' : string,
  'plantId' : string,
  'alloyGrade' : string,
  'dieNo' : string,
}
export type OrderStatus = { 'delayed' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Plant {
  'id' : string,
  'capacityUtilizationPct' : number,
  'totalCapacityMT' : number,
  'name' : string,
  'oeePct' : number,
  'location' : string,
  'activePresses' : bigint,
}
export interface Press {
  'id' : string,
  'status' : PressStatus,
  'activeDie' : string,
  'name' : string,
  'operatorName' : string,
  'shift' : string,
  'currentOrder' : string,
  'alloyGrade' : string,
  'plant' : string,
}
export type PressStatus = { 'idle' : null } |
  { 'breakdown' : null } |
  { 'setup' : null } |
  { 'running' : null };
export interface ProductionMetrics {
  'recoveryPct' : number,
  'containerChangeTime' : number,
  'pressId' : string,
  'cycleTimePerBillet' : number,
  'pullerSpeed' : number,
  'totalProductionMT' : number,
  'pressKgPerHour' : number,
  'dailyTargetMT' : number,
  'sawCycleTime' : number,
  'timestamp' : Time,
  'shiftProductionA' : number,
  'shiftProductionB' : number,
  'shiftProductionC' : number,
  'extrusionSpeed' : number,
  'dailyProductionMT' : number,
  'billetCount' : bigint,
}
export interface QualityRecord {
  'rejectionPctByAlloy' : number,
  'customerComplaints' : bigint,
  'scrapCostImpact' : number,
  'pressId' : string,
  'dimensionalFailurePct' : number,
  'alloyGrade' : string,
  'timestamp' : Time,
  'rejectionPctByDie' : number,
  'dieNo' : string,
  'rootCauseSummary' : string,
  'surfaceDefectCount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addAlarm' : ActorMethod<[Alarm], undefined>,
  'addCostMetrics' : ActorMethod<[CostMetrics], undefined>,
  'addDieMaintenance' : ActorMethod<[DieMaintenance], undefined>,
  'addDowntimeEvent' : ActorMethod<[DowntimeEvent], undefined>,
  'addMachineParameters' : ActorMethod<[MachineParameters], undefined>,
  'addOEEData' : ActorMethod<[OEEData], undefined>,
  'addOrder' : ActorMethod<[Order], undefined>,
  'addPlant' : ActorMethod<[Plant], undefined>,
  'addPress' : ActorMethod<[Press], undefined>,
  'addProductionMetrics' : ActorMethod<[ProductionMetrics], undefined>,
  'addQualityRecord' : ActorMethod<[QualityRecord], undefined>,
  'deletePress' : ActorMethod<[string], undefined>,
  'getActiveAlarms' : ActorMethod<[], Array<Alarm>>,
  'getAllPlants' : ActorMethod<[], Array<Plant>>,
  'getAllPresses' : ActorMethod<[], Array<Press>>,
  'getDowntimeEventsByCategory' : ActorMethod<
    [DowntimeCategory],
    Array<DowntimeEvent>
  >,
  'getMachineParameters' : ActorMethod<[string], MachineParameters>,
  'getOEEData' : ActorMethod<[string], Array<OEEData>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getOverdueDies' : ActorMethod<[Time], Array<DieMaintenance>>,
  'getPlant' : ActorMethod<[string], Plant>,
  'getPress' : ActorMethod<[string], Press>,
  'getPressesByPlant' : ActorMethod<[string], Array<Press>>,
  'getProductionMetrics' : ActorMethod<[string], Array<ProductionMetrics>>,
  'getQualityRecordsByAlloy' : ActorMethod<[string], Array<QualityRecord>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updatePress' : ActorMethod<[Press], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];