/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Alarm {
    id: string;
    pressId: string;
    description: string;
    isActive: boolean;
    timestamp: Time;
    severity: AlarmSeverity;
}
export type Time = bigint;
export interface Plant {
    id: string;
    capacityUtilizationPct: number;
    totalCapacityMT: number;
    name: string;
    oeePct: number;
    location: string;
    activePresses: bigint;
}
export interface ProductionMetrics {
    recoveryPct: number;
    containerChangeTime: number;
    pressId: string;
    cycleTimePerBillet: number;
    pullerSpeed: number;
    totalProductionMT: number;
    pressKgPerHour: number;
    dailyTargetMT: number;
    sawCycleTime: number;
    timestamp: Time;
    shiftProductionA: number;
    shiftProductionB: number;
    shiftProductionC: number;
    extrusionSpeed: number;
    dailyProductionMT: number;
    billetCount: bigint;
}
export interface Order {
    id: string;
    customerName: string;
    status: OrderStatus;
    completedMT: number;
    totalMT: number;
    dueDate: Time;
    workOrderNo: string;
    plantId: string;
    alloyGrade: string;
    dieNo: string;
}
export interface Press {
    id: string;
    status: PressStatus;
    activeDie: string;
    name: string;
    operatorName: string;
    shift: string;
    currentOrder: string;
    alloyGrade: string;
    plant: string;
}
export interface MachineParameters {
    exitTemp: number;
    billetTemp: number;
    pressId: string;
    mainRamPressure: number;
    containerTemp: number;
    dieTemp: number;
    timestamp: Time;
    extrusionPressure: number;
    ramSpeed: number;
    pullerForce: number;
    breakthroughPressure: number;
}
export interface DowntimeEvent {
    id: string;
    mtbfHours: number;
    pressId: string;
    durationMinutes: bigint;
    timestamp: Time;
    category: DowntimeCategory;
    mttrHours: number;
}
export interface OEEData {
    rejectionPct: number;
    reworkPct: number;
    scrapKg: number;
    dieChangeTime: number;
    pressId: string;
    standardSpeed: number;
    idleTime: number;
    pressEfficiencyPct: number;
    breakdownTime: number;
    outputVsRatedCapacityPct: number;
    firstPassYieldPct: number;
    qualityPct: number;
    timestamp: Time;
    availabilityPct: number;
    setupTime: number;
    plannedRunTime: number;
    oeePct: number;
    actualRunTime: number;
    actualSpeed: number;
    performancePct: number;
}
export interface CostMetrics {
    powerConsumptionKwh: number;
    pressId: string;
    date: Time;
    labourEfficiencyPct: number;
    energyCostPerMT: number;
    revenuePerPressPerDay: number;
    productionCostPerMT: number;
    scrapCost: number;
}
export interface QualityRecord {
    rejectionPctByAlloy: number;
    customerComplaints: bigint;
    scrapCostImpact: number;
    pressId: string;
    dimensionalFailurePct: number;
    alloyGrade: string;
    timestamp: Time;
    rejectionPctByDie: number;
    dieNo: string;
    rootCauseSummary: string;
    surfaceDefectCount: bigint;
}
export interface DieMaintenance {
    shotsCompleted: bigint;
    changeFrequency: bigint;
    maintenanceDue: Time;
    dieNo: string;
    shotLife: bigint;
    lastMaintenanceDate: Time;
}
export enum AlarmSeverity {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum DowntimeCategory {
    dieFailure = "dieFailure",
    other = "other",
    operatorDelay = "operatorDelay",
    billetQuality = "billetQuality",
    powerFailure = "powerFailure",
    mechanicalFailure = "mechanicalFailure"
}
export enum OrderStatus {
    delayed = "delayed",
    open = "open",
    completed = "completed",
    inProgress = "inProgress"
}
export enum PressStatus {
    idle = "idle",
    breakdown = "breakdown",
    setup = "setup",
    running = "running"
}
export interface backendInterface {
    addAlarm(alarm: Alarm): Promise<void>;
    addCostMetrics(metrics: CostMetrics): Promise<void>;
    addDieMaintenance(maintenance: DieMaintenance): Promise<void>;
    addDowntimeEvent(event: DowntimeEvent): Promise<void>;
    addMachineParameters(params: MachineParameters): Promise<void>;
    addOEEData(data: OEEData): Promise<void>;
    addOrder(order: Order): Promise<void>;
    addPlant(plant: Plant): Promise<void>;
    addPress(press: Press): Promise<void>;
    addProductionMetrics(metrics: ProductionMetrics): Promise<void>;
    addQualityRecord(record: QualityRecord): Promise<void>;
    deletePress(id: string): Promise<void>;
    getActiveAlarms(): Promise<Array<Alarm>>;
    getAllPlants(): Promise<Array<Plant>>;
    getAllPresses(): Promise<Array<Press>>;
    getDowntimeEventsByCategory(category: DowntimeCategory): Promise<Array<DowntimeEvent>>;
    getMachineParameters(pressId: string): Promise<MachineParameters>;
    getOEEData(pressId: string): Promise<Array<OEEData>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getOverdueDies(currentTime: Time): Promise<Array<DieMaintenance>>;
    getPlant(id: string): Promise<Plant>;
    getPress(id: string): Promise<Press>;
    getPressesByPlant(plantId: string): Promise<Array<Press>>;
    getProductionMetrics(pressId: string): Promise<Array<ProductionMetrics>>;
    getQualityRecordsByAlloy(alloy: string): Promise<Array<QualityRecord>>;
    seedSampleData(): Promise<void>;
    updatePress(press: Press): Promise<void>;
}
import type { Alarm as _Alarm, AlarmSeverity as _AlarmSeverity, DowntimeCategory as _DowntimeCategory, DowntimeEvent as _DowntimeEvent, Order as _Order, OrderStatus as _OrderStatus, Press as _Press, PressStatus as _PressStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAlarm(arg0: Alarm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlarm(to_candid_Alarm_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlarm(to_candid_Alarm_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCostMetrics(arg0: CostMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCostMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCostMetrics(arg0);
            return result;
        }
    }
    async addDieMaintenance(arg0: DieMaintenance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDieMaintenance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDieMaintenance(arg0);
            return result;
        }
    }
    async addDowntimeEvent(arg0: DowntimeEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDowntimeEvent(to_candid_DowntimeEvent_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDowntimeEvent(to_candid_DowntimeEvent_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMachineParameters(arg0: MachineParameters): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMachineParameters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMachineParameters(arg0);
            return result;
        }
    }
    async addOEEData(arg0: OEEData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOEEData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOEEData(arg0);
            return result;
        }
    }
    async addOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrder(to_candid_Order_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrder(to_candid_Order_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPlant(arg0: Plant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlant(arg0);
            return result;
        }
    }
    async addPress(arg0: Press): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPress(to_candid_Press_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPress(to_candid_Press_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProductionMetrics(arg0: ProductionMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionMetrics(arg0);
            return result;
        }
    }
    async addQualityRecord(arg0: QualityRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQualityRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQualityRecord(arg0);
            return result;
        }
    }
    async deletePress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePress(arg0);
            return result;
        }
    }
    async getActiveAlarms(): Promise<Array<Alarm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlarms();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlarms();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlants(): Promise<Array<Plant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlants();
            return result;
        }
    }
    async getAllPresses(): Promise<Array<Press>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPresses();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPresses();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDowntimeEventsByCategory(arg0: DowntimeCategory): Promise<Array<DowntimeEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDowntimeEventsByCategory(to_candid_DowntimeCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDowntimeEventsByCategory(to_candid_DowntimeCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMachineParameters(arg0: string): Promise<MachineParameters> {
        if (this.processError) {
            try {
                const result = await this.actor.getMachineParameters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMachineParameters(arg0);
            return result;
        }
    }
    async getOEEData(arg0: string): Promise<Array<OEEData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOEEData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOEEData(arg0);
            return result;
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueDies(arg0: Time): Promise<Array<DieMaintenance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueDies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueDies(arg0);
            return result;
        }
    }
    async getPlant(arg0: string): Promise<Plant> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlant(arg0);
            return result;
        }
    }
    async getPress(arg0: string): Promise<Press> {
        if (this.processError) {
            try {
                const result = await this.actor.getPress(arg0);
                return from_candid_Press_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPress(arg0);
            return from_candid_Press_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPressesByPlant(arg0: string): Promise<Array<Press>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPressesByPlant(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPressesByPlant(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionMetrics(arg0: string): Promise<Array<ProductionMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionMetrics(arg0);
            return result;
        }
    }
    async getQualityRecordsByAlloy(arg0: string): Promise<Array<QualityRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQualityRecordsByAlloy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQualityRecordsByAlloy(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async updatePress(arg0: Press): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePress(to_candid_Press_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePress(to_candid_Press_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AlarmSeverity_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlarmSeverity): AlarmSeverity {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Alarm_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alarm): Alarm {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DowntimeCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DowntimeCategory): DowntimeCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_DowntimeEvent_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DowntimeEvent): DowntimeEvent {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PressStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PressStatus): PressStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Press_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Press): Press {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pressId: string;
    description: string;
    isActive: boolean;
    timestamp: _Time;
    severity: _AlarmSeverity;
}): {
    id: string;
    pressId: string;
    description: string;
    isActive: boolean;
    timestamp: Time;
    severity: AlarmSeverity;
} {
    return {
        id: value.id,
        pressId: value.pressId,
        description: value.description,
        isActive: value.isActive,
        timestamp: value.timestamp,
        severity: from_candid_AlarmSeverity_n20(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PressStatus;
    activeDie: string;
    name: string;
    operatorName: string;
    shift: string;
    currentOrder: string;
    alloyGrade: string;
    plant: string;
}): {
    id: string;
    status: PressStatus;
    activeDie: string;
    name: string;
    operatorName: string;
    shift: string;
    currentOrder: string;
    alloyGrade: string;
    plant: string;
} {
    return {
        id: value.id,
        status: from_candid_PressStatus_n25(_uploadFile, _downloadFile, value.status),
        activeDie: value.activeDie,
        name: value.name,
        operatorName: value.operatorName,
        shift: value.shift,
        currentOrder: value.currentOrder,
        alloyGrade: value.alloyGrade,
        plant: value.plant
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    mtbfHours: number;
    pressId: string;
    durationMinutes: bigint;
    timestamp: _Time;
    category: _DowntimeCategory;
    mttrHours: number;
}): {
    id: string;
    mtbfHours: number;
    pressId: string;
    durationMinutes: bigint;
    timestamp: Time;
    category: DowntimeCategory;
    mttrHours: number;
} {
    return {
        id: value.id,
        mtbfHours: value.mtbfHours,
        pressId: value.pressId,
        durationMinutes: value.durationMinutes,
        timestamp: value.timestamp,
        category: from_candid_DowntimeCategory_n30(_uploadFile, _downloadFile, value.category),
        mttrHours: value.mttrHours
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: _OrderStatus;
    completedMT: number;
    totalMT: number;
    dueDate: _Time;
    workOrderNo: string;
    plantId: string;
    alloyGrade: string;
    dieNo: string;
}): {
    id: string;
    customerName: string;
    status: OrderStatus;
    completedMT: number;
    totalMT: number;
    dueDate: Time;
    workOrderNo: string;
    plantId: string;
    alloyGrade: string;
    dieNo: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n35(_uploadFile, _downloadFile, value.status),
        completedMT: value.completedMT,
        totalMT: value.totalMT,
        dueDate: value.dueDate,
        workOrderNo: value.workOrderNo,
        plantId: value.plantId,
        alloyGrade: value.alloyGrade,
        dieNo: value.dieNo
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): AlarmSeverity {
    return "warning" in value ? AlarmSeverity.warning : "info" in value ? AlarmSeverity.info : "critical" in value ? AlarmSeverity.critical : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    breakdown: null;
} | {
    setup: null;
} | {
    running: null;
}): PressStatus {
    return "idle" in value ? PressStatus.idle : "breakdown" in value ? PressStatus.breakdown : "setup" in value ? PressStatus.setup : "running" in value ? PressStatus.running : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dieFailure: null;
} | {
    other: null;
} | {
    operatorDelay: null;
} | {
    billetQuality: null;
} | {
    powerFailure: null;
} | {
    mechanicalFailure: null;
}): DowntimeCategory {
    return "dieFailure" in value ? DowntimeCategory.dieFailure : "other" in value ? DowntimeCategory.other : "operatorDelay" in value ? DowntimeCategory.operatorDelay : "billetQuality" in value ? DowntimeCategory.billetQuality : "powerFailure" in value ? DowntimeCategory.powerFailure : "mechanicalFailure" in value ? DowntimeCategory.mechanicalFailure : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    delayed: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): OrderStatus {
    return "delayed" in value ? OrderStatus.delayed : "open" in value ? OrderStatus.open : "completed" in value ? OrderStatus.completed : "inProgress" in value ? OrderStatus.inProgress : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alarm>): Array<Alarm> {
    return value.map((x)=>from_candid_Alarm_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Press>): Array<Press> {
    return value.map((x)=>from_candid_Press_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DowntimeEvent>): Array<DowntimeEvent> {
    return value.map((x)=>from_candid_DowntimeEvent_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n33(_uploadFile, _downloadFile, x));
}
function to_candid_AlarmSeverity_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlarmSeverity): _AlarmSeverity {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Alarm_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alarm): _Alarm {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DowntimeCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DowntimeCategory): _DowntimeCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_DowntimeEvent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DowntimeEvent): _DowntimeEvent {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PressStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PressStatus): _PressStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Press_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Press): _Press {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: OrderStatus;
    completedMT: number;
    totalMT: number;
    dueDate: Time;
    workOrderNo: string;
    plantId: string;
    alloyGrade: string;
    dieNo: string;
}): {
    id: string;
    customerName: string;
    status: _OrderStatus;
    completedMT: number;
    totalMT: number;
    dueDate: _Time;
    workOrderNo: string;
    plantId: string;
    alloyGrade: string;
    dieNo: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        completedMT: value.completedMT,
        totalMT: value.totalMT,
        dueDate: value.dueDate,
        workOrderNo: value.workOrderNo,
        plantId: value.plantId,
        alloyGrade: value.alloyGrade,
        dieNo: value.dieNo
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: PressStatus;
    activeDie: string;
    name: string;
    operatorName: string;
    shift: string;
    currentOrder: string;
    alloyGrade: string;
    plant: string;
}): {
    id: string;
    status: _PressStatus;
    activeDie: string;
    name: string;
    operatorName: string;
    shift: string;
    currentOrder: string;
    alloyGrade: string;
    plant: string;
} {
    return {
        id: value.id,
        status: to_candid_PressStatus_n15(_uploadFile, _downloadFile, value.status),
        activeDie: value.activeDie,
        name: value.name,
        operatorName: value.operatorName,
        shift: value.shift,
        currentOrder: value.currentOrder,
        alloyGrade: value.alloyGrade,
        plant: value.plant
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    pressId: string;
    description: string;
    isActive: boolean;
    timestamp: Time;
    severity: AlarmSeverity;
}): {
    id: string;
    pressId: string;
    description: string;
    isActive: boolean;
    timestamp: _Time;
    severity: _AlarmSeverity;
} {
    return {
        id: value.id,
        pressId: value.pressId,
        description: value.description,
        isActive: value.isActive,
        timestamp: value.timestamp,
        severity: to_candid_AlarmSeverity_n3(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    mtbfHours: number;
    pressId: string;
    durationMinutes: bigint;
    timestamp: Time;
    category: DowntimeCategory;
    mttrHours: number;
}): {
    id: string;
    mtbfHours: number;
    pressId: string;
    durationMinutes: bigint;
    timestamp: _Time;
    category: _DowntimeCategory;
    mttrHours: number;
} {
    return {
        id: value.id,
        mtbfHours: value.mtbfHours,
        pressId: value.pressId,
        durationMinutes: value.durationMinutes,
        timestamp: value.timestamp,
        category: to_candid_DowntimeCategory_n7(_uploadFile, _downloadFile, value.category),
        mttrHours: value.mttrHours
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    delayed: null;
} | {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == OrderStatus.delayed ? {
        delayed: null
    } : value == OrderStatus.open ? {
        open: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PressStatus): {
    idle: null;
} | {
    breakdown: null;
} | {
    setup: null;
} | {
    running: null;
} {
    return value == PressStatus.idle ? {
        idle: null
    } : value == PressStatus.breakdown ? {
        breakdown: null
    } : value == PressStatus.setup ? {
        setup: null
    } : value == PressStatus.running ? {
        running: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlarmSeverity): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == AlarmSeverity.warning ? {
        warning: null
    } : value == AlarmSeverity.info ? {
        info: null
    } : value == AlarmSeverity.critical ? {
        critical: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DowntimeCategory): {
    dieFailure: null;
} | {
    other: null;
} | {
    operatorDelay: null;
} | {
    billetQuality: null;
} | {
    powerFailure: null;
} | {
    mechanicalFailure: null;
} {
    return value == DowntimeCategory.dieFailure ? {
        dieFailure: null
    } : value == DowntimeCategory.other ? {
        other: null
    } : value == DowntimeCategory.operatorDelay ? {
        operatorDelay: null
    } : value == DowntimeCategory.billetQuality ? {
        billetQuality: null
    } : value == DowntimeCategory.powerFailure ? {
        powerFailure: null
    } : value == DowntimeCategory.mechanicalFailure ? {
        mechanicalFailure: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
